version: "3.2"
services:
  whatsup:
    image: fijimunkii/whatsup:latest
    container_name: whatsup
    environment:
      - 'S3_BUCKET=whatsup-myapp'
    restart: always
    ports:
      - target: 5555
        published: 80
        protocol: tcp
