version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=myapp.com"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=whoami@myapp.com"
      - "--acme.storage=acme.json"
      - "--acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  whatsup:
    image: fijimunkii/whatsup:latest
    container_name: whatsup
    environment:
      - 'HTTPS=true'
      - 'S3_BUCKET=whatsup-myapp'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whatsup"
      - "traefik.port=5555"
      - "traefik.frontend.rule=Host:whatsup.myapp.com"
    restart: always
